package org.agmas.harpymodloader.client.mixin;

import dev.doctor4t.wathe.api.Role;
import dev.doctor4t.wathe.cca.GameWorldComponent;
import dev.doctor4t.wathe.client.gui.RoleAnnouncementTexts;
import dev.doctor4t.wathe.game.GameFunctions;
import net.fabricmc.loader.impl.util.log.Log;
import net.fabricmc.loader.impl.util.log.LogCategory;
import net.minecraft.client.MinecraftClient;
import net.minecraft.text.Text;
import org.agmas.harpymodloader.Harpymodloader;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;


@Mixin(RoleAnnouncementTexts.RoleAnnouncementText.class)
public abstract class InnocenceReliantWinTextMixin {

    @Inject(method = "getEndText", at = @At("HEAD"), cancellable = true)
    private void b(GameFunctions.WinStatus status, Text winner, CallbackInfoReturnable<Text> cir) {
        GameWorldComponent gameWorldComponent = (GameWorldComponent) GameWorldComponent.KEY.get(MinecraftClient.getInstance().player.getWorld());
        if (Harpymodloader.autogeneratedAnnouncements_flip.get((RoleAnnouncementTexts.RoleAnnouncementText)(Object)this) != null) {
            Role role = Harpymodloader.autogeneratedAnnouncements_flip.get((RoleAnnouncementTexts.RoleAnnouncementText)(Object)this);
            switch (status) {
                case TIME:
                case PASSENGERS:
                    cir.setReturnValue(role.isInnocent() ? RoleAnnouncementTexts.CIVILIAN.winText : RoleAnnouncementTexts.KILLER.getLoseText());
                    cir.cancel();
                    break;
                case KILLERS:
                    cir.setReturnValue(role.isInnocent() ? RoleAnnouncementTexts.CIVILIAN.getLoseText() : RoleAnnouncementTexts.KILLER.winText);
                    cir.cancel();
                    break;
            }
        }
    }
}
